config:
  outputs: |
    [OUTPUT]
        Name                 opentelemetry
        Match                *
        Host                 my-otel-demo-otelcol.otel-demo.svc.cluster.local
        Port                 4318
        Logs_uri             /v1/logs
        Log_response_payload True
        Tls                  On
        Tls.verify           Off
        # add user-defined labels
        add_label            app fluent-bit
