components:
  frontend:
    resources:
      limits:
        memory: 400Mi

opentelemetry-collector:
  resources:
    limits:
      memory: 640Mi
  config:
    service:
      pipelines:
        traces:
          processors: [memory_limiter, batch]
          exporters: [otlp, spanmetrics]
        metrics:
          receivers: [otlp, spanmetrics]
          processors: [memory_limiter, filter/ottl, transform, batch]
          exporters: [prometheus]
