jaeger:
  allInOne:
    args:
      # Modify max-trace limit
      - "--memory.max-traces"
      - "100000"
      - "--query.base-path"
      - "/jaeger/ui"
      - "--prometheus.server-url"
      - 'http://{{ include "otel-demo.name" . }}-prometheus-server:9090'
    resources:
      limits:
        memory: 640Mi

components:
  frontend:
    resources:
      limits:
        memory: 400Mi

opentelemetry-collector:
  resources:
    limits:
      memory: 640Mi
  config:
    service:
      pipelines:
        traces:
          processors: [memory_limiter, batch]
          exporters: [otlp, spanmetrics]
        metrics:
          receivers: [otlp, spanmetrics]
          processors: [memory_limiter, filter/ottl, transform, batch]
          exporters: [prometheus]
