config:
  outputs: |
    [OUTPUT]
        name              loki
        match             *
        host              my-otel-demo-loki.otel-demo.svc.cluster.local
        labels            job=fluentbit
        auto_kubernetes_labels on
